[package]
name = "pathfinder-wasm"
version = "0.1.0"
authors = ["Peter Leeh <leeh123peter@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "=0.2.34"
js-sys = "0.3"
pathfinding = "2.1"
# rand = "0.8"