[package]
name = "pathfinder-wasm"
version = "0.1.0"
authors = ["Peter Leeh <leeh123peter@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.39"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["console"] }
pathfinding = "2.1"